'use strict';

module.exports = {
    'CHECKOUT_BRANCH':'CHECKOUT_BRANCH',
    'BUILD_PROMO': 'BUILD_PROMO',
    'COPY_PROD': 'COPY_PROD',
    'CHECKOUT_CLIENT_BRANCH': 'CHECKOUT_CLIENT_BRANCH',
    'PUSH_TO_CLIENT': 'PUSH_TO_CLIENT',
    'MERGE_CLIENT_TO_MASTER': 'MERGE_CLIENT_TO_MASTER',
    'PUSH_PROMOTION': 'PUSH_PROMOTION',
    'MERGE_PROMO_TO_MASTER': 'MERGE_PROMO_TO_MASTER',
    'ON_COMPLETE_RELEASE': 'ON_COMPLETE_RELEASE',
}